### ISSUE TITLE
Use as an object pool?

### ISSUE THREAD

**Issue by edwinyzh** [ronaldobim/PascalDBPoolConnection#4]
Great job! It seems can also be used as an object pool??

I use xe4 and I hope I can add support for that compiler ;)

**Comment by ronaldobim** [comment]
Yes, today you can use TComponent pool, but I think we can use Generics to allow any object. Like this. Pool.GetConnectio<TZConnection>. XE4 suports generics?

**Comment by edwinyzh** [comment]
Oops, sorry, I asked before actually trying the compilation - just tested and **it compiles with XE4**!
That being said, XE4 supports generics. 

Yes, you are right, I noticed it's currently a 'TComponent pool'. Can you just change all `TComponent` to `TObject`?

**Comment by ronaldobim** [comment]
Yes, see de last commit [3e799f3](https://github.com/ronaldobim/PascalDBPoolConnection/commit/3e799f39718560dde15fb8232dd3fc870163610c)

**Comment by edwinyzh** [comment]
Thanks and I confirm it compiles on my side ;)
